dependencies:
- role: ansible-role-unarchive-deps
  version: v1.1.5
- role: ansible-role-bash
  version: v1.1.6
galaxy_info:
  author: Andrew Rothstein
  company: PointState Capital
  description: installs liquibase
  galaxy_tags:
  - development
  license:
  - MIT
  min_ansible_version: 2.0
  platforms:
  - name: Debian
    versions:
    - buster
    - stretch
  - name: EL
    versions:
    - 7
    - 8
  - name: Fedora
    versions:
    - 31
    - 32
  - name: Ubuntu
    versions:
    - bionic
    - focal
    - xenial
