---

- name: Install HAProxy
  apt:
    name: "haproxy"
    state: "present"

- name: Configure HAProxy
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    backup: yes