---
# This playbook deploys the whole application stack for a jenkins.

# TODO: Verificar quando for fazer os jenkins slave https://github.com/lean-delivery/ansible-role-jenkins-slave

- hosts: localhost
  tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'

- name: Install Java 8
  hosts: localhost
  roles:
    - role: ansible-role-java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk

- name: Install Liquibase
  hosts: localhost
  roles:
    - ansible-role-liquibase

- name: Install Docker
  become: true
  hosts: localhost
  roles:
    - ansible-role-docker

- name: Install Terraform
  hosts: localhost
  roles:
    - role: ansible-role-terraform

- name: Install Kubectl
  hosts: localhost
  become: true
  roles:
    - role: ansible-role-kubectl

- name: Install Jenkins
  hosts: localhost
  become: true
  vars:
    jenkins_hostname: localhost
    java_packages:
      - openjdk-8-jdk
  roles:
    - role: ansible-role-jenkins

#- name: Applies HAProxy config for SSL
#  hosts: localhost
#  become: true
#  roles:
#    - role: ansible-role-haproxy